### ISSUE TITLE
About me sticking to the left in popouts

### ISSUE THREAD

**Issue by ToasterUwU** [CelestialReaver/BetterDiscord#1]
First of all: I love this Theme! Its the first one i was really happy with after trying like 10 different one, and it also works smoothly with most plugins. Except one, which i think is more the fault of the other plugin than this theme. So: 10/10 great job

Now to the problem.
Everything so far looks right and well, except the one thing i will attach as screenshot, described in the title:
![image](https://user-images.githubusercontent.com/43654377/184786930-30227f89-834c-4872-b4b0-2ec439c48e54.png)

I censored everything not important.
Like you can see, the About Me section is sticking to the very left of the popout, not like i would suspect have the same distance to the "wall" as my username.

**Comment by ToasterUwU** [comment]
Just saw this repo is for everything you made for BetterDiscord, so im gonna clarify:

This is about the Synthwave84 Theme

**Comment by CelestialReaver** [comment]
Hey @ToasterUwU ! I appreciate the love! Yes, I def need to fix that. I think it started a few discord updates ago. It's been on my list but I'll let it bubble it up and get it done soon. 

Thank you for reaching out to me. I appreciate it! I'll respond once it's done.

**Comment by ToasterUwU** [comment]
![image](https://user-images.githubusercontent.com/43654377/187706307-5af08c28-1bc0-42bd-bbe9-784c02ebcd55.png)


It looks different now, not sure if thats your handy work or some kind of update accendentially fixing it. @CelestialReaver

**Comment by ToasterUwU** [comment]
Ok, it wasnt you. Its discord showing the backround of people in their accent color or someting like that. 

![image](https://user-images.githubusercontent.com/43654377/187708708-e4a68e04-8bb9-4264-9fab-caf9e16a4132.png)

**Comment by CelestialReaver** [comment]
discord made some big updates - and more on the way - that will impact the UI. i'll be working on the spacing today.

**Comment by CelestialReaver** [comment]
this is all set. i've pushed the change and it should show up for you in 15 minutes or so. it will require completely exiting/stopping discord and reopening. let me know!

![image](https://user-images.githubusercontent.com/331055/187739048-a3c76e8d-952f-419d-b172-7564042d51e0.png)

@ToasterUwU

**Comment by ToasterUwU** [comment]
Hey, dont know why, but the update is not on the Themes Repo. 

The version that is on https://betterdiscord.app/themes is still the 1.0.2 version, which is the same i have, which is the same that isnt updated.

**Comment by CelestialReaver** [comment]
it should automatically work. no need to update the theme.

Sent from Proton Mail mobile

-------- Original Message --------

**Comment by ToasterUwU** [comment]
Yeah, it doesnt work. I turned off my PC, went to bed for 9 hours, woke up and turned my pc back on, it still looks the same. Whatever you changed, didnt get to my client, even tho i restarted Discord and the PC at least 3 times.

**Comment by ToasterUwU** [comment]
@CelestialReaver Is there anything i can do? Or is the only thing i can do wait?

**Comment by CelestialReaver** [comment]
@ToasterUwU - i am not able to reproduce the issue
![image](https://user-images.githubusercontent.com/331055/189190262-47526a8e-a91e-43ff-a8a1-7e77cf6bcac8.png)

it's showing margins for me. is it not for you?

**Comment by ToasterUwU** [comment]
@CelestialReaver Nope. It's not updating in general, the whole theme is broken for me. With embed messages being too long, the profile previews being the standard colors instead of theme colors and more.

I tried a lot of different things already. Uninstaller the theme, reinstalled it. Uninstalled discord, reinstalled it, reinstalled better discord, reinstalled the theme.

It just doesn't work. No matter if I have other plug-ins enabled or if the only thing active.

**Comment by CelestialReaver** [comment]
![image](https://user-images.githubusercontent.com/331055/189210251-bf722bc3-3383-4922-8f8c-8dba441f30e5.png)

i updated the user profiles about 30 mins ago. they should be good after you quit and reopen discord. embeds look fine as well. could you send a screenshot of what you're seeing

**Comment by ToasterUwU** [comment]
Sure, here are some screenshots with little lines to show whats wrong. 
Btw: I just restarted Discord and now the user profiles look better, but they are buggy like the rest.

Embed are too long, they reach over the color things on the left.
![image](https://user-images.githubusercontent.com/43654377/189287976-7e962da7-c2de-4935-be77-dc477c82ee66.png)

That looks even worse when there are buttons, since they just all clip into each other.
![image](https://user-images.githubusercontent.com/43654377/189288057-ada69b34-36f9-4114-a0f9-d553b2fde717.png)

In this censored screenshot you can see that the profil things are transparent in the lower half of the banner, which results in being able to see the messages behind it.
![image](https://user-images.githubusercontent.com/43654377/189288402-bc76e3cb-5d08-45af-9433-c808924a3d15.png)

**Comment by ToasterUwU** [comment]
@CelestialReaverI just noticed that the embed issue also exists in your screenshot. Look closely at the youtube things, the actual box is longer than the side bar with the color.

**Comment by ToasterUwU** [comment]
@CelestialReaver Also just noticed, the banner for people only breaks with profils that dont have a custom banner, but instead the accent color standard banner from Discord. Those have this half transparent issue.

**Comment by ToasterUwU** [comment]
@CelestialReaver Any updates?

**Comment by CelestialReaver** [comment]
@ToasterUwU - this should be all set now. i also updated theming for the new Forums feature Discord is rolling out. let me know.

**Comment by ToasterUwU** [comment]
@CelestialReaver The Profile bug is gone, but the embed messages are still too long, and still overlap with UI elements and all that.

**Comment by CelestialReaver** [comment]
ok - thank you

**Comment by ToasterUwU** [comment]
@CelestialReaver I'm somewhat certain that the problem is that the theme gives extra padding/margin between the elemenst of the Embed message (Title, Description, footer). 
I think so because some embed messages have more overlap than others, and those have more elements to them than the shorter ones. 

I could be wrong, i didnt check the CSS, but it seems to be something like this.

**Comment by CelestialReaver** [comment]
I'm starting work on it later today. Hope to have it resolved an an update pushed. I'll post an update. Thanks for checking in.

-------- Original Message --------
