### ISSUE TITLE
Synthwave 84 - user section and flyout stay gray

### ISSUE THREAD

**Issue by CapoFantasma97** [CelestialReaver/BetterDiscord#4]
Not sure how to call them. These elements aren't changed by the theme.

![immagine](https://user-images.githubusercontent.com/9368910/219470610-42a6f7e8-2027-4cb6-99b9-f489d0b845f2.png)
![immagine](https://user-images.githubusercontent.com/9368910/219470651-178608eb-a3c7-4695-89fd-f06081b180a7.png)

**Comment by CelestialReaver** [comment]
Thanks @CapoFantasma97 ! i'll take a look at this!
