### ISSUE TITLE
Font not loading.

### ISSUE THREAD

**Issue by LaykaKiro** [CelestialReaver/BetterDiscord#5]
The font appears gray and unreadable.
And seems to be having issues generally existing...
![Desktop Screenshot 2023 02 23 - 19 19 30 49](https://user-images.githubusercontent.com/34409251/220866331-92250073-bd74-4a1f-8ee6-905e3740d2d0.png)

**Comment by CelestialReaver** [comment]
hi @LaykaKiro - i am unable to reproduce the font issue you are experiencing. could there be multiple themes enabled? perhaps a plugin that is interferring?
![image](https://user-images.githubusercontent.com/331055/220978222-83023e00-0f3c-4b92-9ae6-c62a047e1b39.png)

**Comment by LaykaKiro** [comment]
Oh, it could possibly be light theme. But the BD Theme page also showed a different font when showing the preview.
Maybe the font was incorrect in the preview. Also I have no other themes enabled.
![2023-02-24 09_11_06-Cemu 2 0-28 (experimental) - FPS_ 120 00  Vulkan   NVIDIA GPU   TitleId_ 0005000](https://user-images.githubusercontent.com/34409251/221052202-2ac1db40-7515-44b6-9850-b112b371b36c.png)

**Comment by f-x1-1** [comment]
Same issue here.
