### ISSUE TITLE
font changed?

### ISSUE THREAD

**Issue by Crevice1nY0rFacts** [CelestialReaver/BetterDiscord#9]
When i first got the theme, I opened it up and the font changed to times new roman. Is this how the font is supposed to be or is it a bug, and can I fix it?
![2023-03-16 (4)](https://user-images.githubusercontent.com/128099911/225764672-ebb6ed3d-f3c2-498f-abea-8951d7d047ff.png)

**Comment by cmdshft** [comment]
I have the same issue. The CSS says "Whitney", which I have installed on my system but it's not working.

**Comment by CapoFantasma97** [comment]
It is broken. You can use a custom CSS script in the BetterDiscord's editor, like this (in my example I use Atkinson Hyperlegible):

```
::-webkit-input-placeholder, body, button, input, select, textarea {
    font-family: "Atkinson Hyperlegible";
}
:root { --customFont: "Atkinson Hyperlegible"; }
```

Have the font of your choice installed on your computer and it will have no issues.
